version: "3"

services:
  next:
    build:      
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: next-container
    hostname: next-server
    tty: true
    environment:
      - STATUS=development
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./frontend/app:/usr/src/app
    restart: always
